[workspace]
members = [
  "playground",
  "buffer",
  "delay",
  "dsp",
  "envelope",
  "filter",
  "grains",
  "interpolation",
  "reverb",
  "trig",
  "waveshape",
  "wavetable", 
  "vector", 
  "fdn", 
  "polytable"
]
exclude = [
  "interp_test"
]
resolver = "1"
