[workspace]
members = [
  "playground",
  "buffer",
  "delay",
  "dsp",
  "envelope",
  "filter",
  "grains",
  "grains2",
  "interpolation",
  "reverb",
  "trig",
  "waveshape",
  "wavetable", "vector", "fdn", "grains2",
]
exclude = [
  "interp_test"
]
resolver = "1"
