[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wavetable = {path = "../wavetable"}
interpolation = {path= "../interpolation"}
cpal = "0.15.2"
anyhow = "1.0.79"
